apiVersion: v1
kind: Service
metadata: 
  name: prod-service-db
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: prod-service-app
  namespace: prod
spec:
  selector:
    app: prod-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
---

apiVersion: v1
kind: Service
metadata:
  name: prod-service-zookeeper
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---

apiVersion: v1
kind: Service
metadata:
  name: prod-service-kafka
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
---

apiVersion: v1
kind: Service
metadata:
  name: prod-service-kafdrop
  namespace: prod
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
