name: Build and Deploy REST API Application

on:
  push:
    branches:
      - main

env:
  ENV: prod
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: "bank_$ENV"
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  DEPLOYMENT_NAME: "$ENV-deployment"
  IMAGE: "bank_$ENV"
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: "Setup Build Publish Deploy to Prod"
    runs-on: ubuntu-latest
    environment: $ENV

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install flake8
        # python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # # - name: Test with pytest
    # #   run: |
    # #     pytest

    - name: Setup Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Configure Docker
      run: |
        gcloud --quiet auth configure-docker
    
    - name: Configure Kubernetes to New Version
      run: |
        gcloud components install gke-gcloud-auth-plugin
    
    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials "$GKE_CLUSTER" --project "$GKE_PROJECT" --zone "$GKE_ZONE"
    
    - name: Build Docker Image
      run: |
        docker build --tag "gcr.io/$GKE_PROJECT/$IMAGE:$TAG" ./app/.
    
    - name: Publish GCR
      run: |
        docker push "gcr.io/$GKE_PROJECT/$IMAGE:$TAG"
    
    - name: Publish GKE
      run: |
        kubectl apply -f "k8s/$ENV/namespace.yaml"
        kubectl apply -f "k8s/$ENV/configmap.yaml"
        kubectl apply -f "k8s/$ENV/secret.yaml"
        kubectl apply -f "k8s/$ENV/deployment.yaml"
        kubectl apply -f "k8s/$ENV/service.yaml"
    
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: "#bank"
      if: always()